=== anibale11/vendor/app/code/Ecombricks/Interception/etc/interception.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© eComBricks. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="type" type="typeType" minOccurs="0" maxOccurs="unbounded">
                    <xs:unique name="uniqueTrait">
                        <xs:annotation>
                            <xs:documentation>Trait type should be unique</xs:documentation>
                        </xs:annotation>
                        <xs:selector xpath="trait" />
                        <xs:field xpath="@type" />
                    </xs:unique>
                    <xs:unique name="uniqueProperty">
                        <xs:annotation>
                            <xs:documentation>Property name should be unique</xs:documentation>
                        </xs:annotation>
                        <xs:selector xpath="property" />
                        <xs:field xpath="@name" />
                    </xs:unique>
                </xs:element>
            </xs:choice>
        </xs:complexType>
        <xs:unique name="uniqueType">
            <xs:annotation>
                <xs:documentation>Type name should be unique</xs:documentation>
            </xs:annotation>
            <xs:selector xpath="type" />
            <xs:field xpath="@name" />
        </xs:unique>
    </xs:element>
    <xs:complexType name="typeType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="trait" type="traitType" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="property" type="propertyType" minOccurs="0" maxOccurs="unbounded" />
        </xs:choice>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
    <xs:complexType name="traitType">
        <xs:attribute name="type" type="xs:string" use="required" />
        <xs:attribute name="disabled" type="xs:boolean" use="optional" />
        <xs:attribute name="sortOrder" type="xs:int" use="optional" />
    </xs:complexType>
    <xs:complexType name="propertyType" mixed="true">
        <xs:sequence>
            <xs:element name="item" type="propertyItemType" minOccurs="0" maxOccurs="unbounded">
                <xs:key name="itemName">
                    <xs:selector xpath="item"></xs:selector>
                    <xs:field xpath="@name"></xs:field>
                </xs:key>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="type" type="propertyTypeType" use="required" />
        <xs:attribute name="scope" type="propertyScopeType" use="optional" />
        <xs:attribute name="disabled" type="xs:boolean" use="optional" />
    </xs:complexType>
    <xs:complexType name="propertyItemType" mixed="true">
        <xs:attribute name="name" use="required" />
    </xs:complexType>
    <xs:simpleType name="propertyTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="string" />
            <xs:enumeration value="integer" />
            <xs:enumeration value="float" />
            <xs:enumeration value="boolean" />
            <xs:enumeration value="array" />
            <xs:enumeration value="object" />
            <xs:enumeration value="copy" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="propertyScopeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="private" />
            <xs:enumeration value="protected" />
            <xs:enumeration value="public" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== anibale11/vendor/app/code/Ecombricks/VendorBackend/etc/interception.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© eComBricks. All rights reserved.
 * See LICENSE.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:ecombricks:module:Ecombricks_Interception:etc/interception.xsd">
    <type name="Magento\Framework\Url">
        <property name="vendorParameterActionPathPatterns" type="array">
            <item name="adminDashboard">#^admin/admin/dashboard#</item>
        </property>
    </type>
    <type name="Magento\Backend\Block\Widget\Tabs">
        <trait type="Ecombricks\VendorBackend\Block\Widget\Tabs\RenderTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Backend\Block\Dashboard\AbstractDashboard">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Backend\Block\Dashboard\Grid">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Backend\Block\Dashboard\Grids">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Backend\Helper\Dashboard\Order">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Backend\Controller\Adminhtml\Dashboard">
        <trait type="Ecombricks\VendorBackend\Controller\Adminhtml\Dashboard\VendorTrait" sortOrder="-80" />
    </type>
</config>

=== anibale11/vendor/app/code/Ecombricks/VendorCatalog/etc/interception.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© eComBricks. All rights reserved.
 * See LICENSE.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:ecombricks:module:Ecombricks_Interception:etc/interception.xsd">
    <type name="Magento\Catalog\Model\Product">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\Vendor\Framework\Model\VendorTrait" sortOrder="-90" />
        <property name="vendorManagement" type="object">Ecombricks\Vendor\Model\VendorManagement</property>
    </type>
    <type name="Magento\Catalog\Model\Product\Link">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Catalog\Model\Product\Type">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Catalog\Model\ProductFactory">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Catalog\Model\ResourceModel\Product">
        <trait type="Ecombricks\Vendor\Framework\Model\ResourceModel\Db\VendorTrait" sortOrder="-100" />
        <property name="vendorTable" type="string">ecombricks_vendor_catalog_product_entity</property>
    </type>
    <type name="Magento\Catalog\Model\ResourceModel\Product\Collection">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\Vendor\Framework\Model\ResourceModel\Db\Collection\VendorTrait" sortOrder="-90" />
        <trait type="Ecombricks\VendorCatalog\Model\ResourceModel\Product\Collection\VendorTrait" sortOrder="-80" />
        <property name="vendorManagement" type="object">Ecombricks\Vendor\Model\VendorManagement</property>
        <property name="vendorTable" type="string">ecombricks_vendor_catalog_product_entity</property>
    </type>
    <type name="Magento\Catalog\Model\ResourceModel\Product\CollectionFactory">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Catalog\Model\ResourceModel\Product\Link\Product\CollectionFactory">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Catalog\Model\Layer\FilterList">
        <trait type="Ecombricks\VendorCatalog\Model\Layer\FilterList\VendorTrait" />
    </type>
    <type name="Magento\Catalog\Model\Product\Compare\ListCompare">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Catalog\Model\Product\Compare\ListCompareFactory">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Catalog\Model\ResourceModel\Product\Compare\Item\CollectionFactory">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Catalog\Ui\DataProvider\Product\ProductDataProvider">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Catalog\Ui\DataProvider\Product\Form\ProductDataProvider">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <property name="pool" type="copy">pool</property>
    </type>
    <type name="Magento\Catalog\Ui\DataProvider\Product\Form\Modifier\AbstractModifier">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Catalog\Controller\Adminhtml\Product\Builder">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <property name="vendorResultPageFactory" type="object">Magento\Framework\View\Result\PageFactory</property>
        <property name="vendorUrlBuilder" type="object">Magento\Framework\UrlInterface</property>
        <property name="vendorBackendUrl" type="object">Magento\Backend\Model\UrlInterface</property>
    </type>
</config>

=== anibale11/vendor/app/code/Ecombricks/VendorUi/etc/interception.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© eComBricks. All rights reserved.
 * See LICENSE.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:ecombricks:module:Ecombricks_Interception:etc/interception.xsd">
    <type name="Magento\Framework\Url">
        <property name="vendorParameterActionPathPatterns" type="array">
            <item name="adminMui">#^admin/mui#</item>
        </property>
    </type>
    <type name="Magento\Framework\View\Layout\Generator\UiComponent">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Framework\View\Element\UiComponentFactory">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Ui\DataProvider\Modifier\Pool">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
</config>

=== anibale11/vendor/app/code/Ecombricks/VendorAuthorization/etc/interception.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© eComBricks. All rights reserved.
 * See LICENSE.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:ecombricks:module:Ecombricks_Interception:etc/interception.xsd">
    <type name="Magento\Framework\Acl\AclResource\Config\SchemaLocator">
        <trait type="Ecombricks\VendorAuthorization\Framework\Acl\AclResource\Config\SchemaLocator\VendorTrait" sortOrder="-100" />
        <property name="vendorUrnResolver" type="object">Magento\Framework\Config\Dom\UrnResolver</property>
    </type>
    <type name="Magento\Framework\Acl\AclResource\Config\Converter\Dom">
        <trait type="Ecombricks\VendorAuthorization\Framework\Acl\AclResource\Config\Converter\Dom\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Framework\Acl\AclResource\Provider">
        <trait type="Ecombricks\VendorAuthorization\Framework\Acl\AclResource\Provider\VendorTrait" sortOrder="-100" />
        <property name="vendorAclDataCache" type="object">Magento\Framework\Acl\Data\CacheInterface</property>
        <property name="vendorAclDataCacheKey" type="string">provider_vendor_acl_resources_cache</property>
        <property name="vendorSerializer" type="object">Magento\Framework\Serialize\Serializer\Json</property>
        <property name="vendorResourceTreeBuilder" type="object">Ecombricks\VendorAuthorization\Framework\Acl\AclResource\VendorTreeBuilder</property>
    </type>
    <type name="Magento\Authorization\Model\Role">
        <trait type="Ecombricks\Vendor\Framework\VendorFlagTrait" sortOrder="-100" />
        <trait type="Ecombricks\Vendor\Framework\Model\VendorFlagTrait" sortOrder="-90" />
    </type>
    <type name="Magento\Authorization\Model\RoleFactory">
        <trait type="Ecombricks\Vendor\Framework\VendorFlagTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Authorization\Model\ResourceModel\Role">
        <trait type="Ecombricks\Vendor\Framework\Model\ResourceModel\Db\VendorFlagTrait" sortOrder="-100" />
        <property name="isVendorTable" type="string">ecombricks_vendor_authorization_role</property>
    </type>
    <type name="Magento\Authorization\Model\ResourceModel\Role\Collection">
        <trait type="Ecombricks\Vendor\Framework\VendorFlagTrait" sortOrder="-100" />
        <trait type="Ecombricks\Vendor\Framework\Model\ResourceModel\Db\Collection\VendorFlagTrait" sortOrder="-90" />
        <property name="isVendorTable" type="string">ecombricks_vendor_authorization_role</property>
    </type>
    <type name="Magento\Authorization\Model\ResourceModel\Role\CollectionFactory">
        <trait type="Ecombricks\Vendor\Framework\VendorFlagTrait" sortOrder="-100" />
    </type>
</config>

=== anibale11/vendor/app/code/Ecombricks/VendorMultishipping/etc/interception.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© eComBricks. All rights reserved.
 * See LICENSE.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:ecombricks:module:Ecombricks_Interception:etc/interception.xsd">
    <type name="Magento\Framework\Url">
        <property name="vendorParameterActionPathPatterns" type="array">
            <item name="multishippingCheckout">#^multishipping/checkout#</item>
        </property>
    </type>
    <type name="Magento\Multishipping\Model\Checkout\Type\Multishipping">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\VendorMultishipping\Model\Checkout\Type\Multishipping\VendorTrait" sortOrder="-90" />
    </type>
    <type name="Magento\Multishipping\Controller\Checkout">
        <property name="vendorCheckoutSession" type="object">Magento\Checkout\Model\Session</property>
        <property name="vendorMultishippingCheckout" type="object">Magento\Multishipping\Model\Checkout\Type\Multishipping</property>
    </type>
    <type name="Magento\Multishipping\Controller\Checkout\Index">
        <trait type="Ecombricks\VendorMultishipping\Controller\Checkout\Index\VendorTrait" sortOrder="-90" />
    </type>
    <type name="Magento\Multishipping\Controller\Checkout\Address">
        <property name="vendorCheckoutSession" type="object">Magento\Checkout\Model\Session</property>
        <property name="vendorMultishippingCheckout" type="object">Magento\Multishipping\Model\Checkout\Type\Multishipping</property>
    </type>
</config>

=== anibale11/vendor/app/code/Ecombricks/VendorWishlist/etc/interception.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© eComBricks. All rights reserved.
 * See LICENSE.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:ecombricks:module:Ecombricks_Interception:etc/interception.xsd">
    <type name="Magento\Framework\Url">
        <property name="vendorParameterActionPathPatterns" type="array">
            <item name="wishlist">#^wishlist#</item>
        </property>
    </type>
    <type name="Magento\Wishlist\Model\Wishlist">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Wishlist\Model\WishlistFactory">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Wishlist\Model\ResourceModel\Item\Collection">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\Vendor\Framework\Model\ResourceModel\Db\Collection\VendorTrait" sortOrder="-90" />
        <property name="vendorManagement" type="object">Ecombricks\Vendor\Model\VendorManagement</property>
        <property name="vendorTable" type="string">ecombricks_vendor_catalog_product_entity</property>
        <property name="mainTableEntityIdFieldName" type="string">product_id</property>
        <property name="vendorTableEntityIdFieldName" type="string">entity_id</property>
    </type>
    <type name="Magento\Wishlist\Model\ResourceModel\Item\CollectionFactory">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
</config>

=== anibale11/vendor/app/code/Ecombricks/VendorCheckout/etc/interception.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© eComBricks. All rights reserved.
 * See LICENSE.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:ecombricks:module:Ecombricks_Interception:etc/interception.xsd">
    <type name="Magento\Framework\Url">
        <property name="vendorParameterActionPathPatterns" type="array">
            <item name="checkout">#^checkout#</item>
        </property>
    </type>
    <type name="Magento\Checkout\Model\Session">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\VendorCheckout\Model\Session\VendorTrait" sortOrder="-90" />
        <property name="vendorManagement" type="object">Ecombricks\Vendor\Model\VendorManagement</property>
    </type>
    <type name="Magento\Checkout\Model\Cart">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\VendorCheckout\Model\Cart\VendorTrait" sortOrder="-90" />
    </type>
    <type name="Magento\Checkout\Model\Type\Onepage">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\VendorCheckout\Model\Type\Onepage\VendorTrait" sortOrder="-90" />
    </type>
    <type name="Magento\Checkout\Model\Type\OnepageFactory">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Checkout\Model\Sidebar">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Checkout\Model\CompositeConfigProvider">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\VendorCheckout\Model\CompositeConfigProvider\VendorTrait" sortOrder="-90" />
        <property name="vendorConfigProviders" type="copy">configProviders</property>
    </type>
    <type name="Magento\Checkout\CustomerData\Cart">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\VendorCheckout\CustomerData\Cart\VendorTrait" sortOrder="-90" />
        <property name="vendorUrlBuilder" type="object">Magento\Framework\UrlInterface</property>
    </type>
    <type name="Magento\Checkout\Block\Cart\AbstractCart">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\Vendor\Framework\View\Element\AbstractBlock\VendorTrait" sortOrder="-90" />
    </type>
    <type name="Magento\Checkout\Controller\Cart\Add">
        <trait type="Ecombricks\VendorCheckout\Controller\Cart\Add\VendorTrait" sortOrder="-90" />
        <property name="vendorStoreManager" type="object">Magento\Store\Model\StoreManagerInterface</property>
        <property name="vendorProductRepository" type="object">Magento\Catalog\Api\ProductRepositoryInterface</property>
    </type>
    <type name="Magento\Checkout\Block\Cart\Crosssell">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\Vendor\Framework\View\Element\AbstractBlock\VendorTrait" sortOrder="-90" />
    </type>
    <type name="Magento\Checkout\Block\Onepage">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\Vendor\Framework\View\Element\AbstractBlock\VendorTrait" sortOrder="-90" />
    </type>
    <type name="Magento\Checkout\Controller\Cart\Index">
        <trait type="Ecombricks\VendorCheckout\Controller\Cart\Index\VendorTrait" sortOrder="-80" />
        <property name="vendorManagement" type="object">Ecombricks\Vendor\Model\VendorManagement</property>
    </type>
    <type name="Magento\Checkout\Controller\Onepage">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\VendorCheckout\Controller\Onepage\VendorTrait" sortOrder="-90" />
        <property name="vendorOnepageCheckout" type="object">Magento\Checkout\Model\Type\Onepage</property>
        <property name="vendorCheckoutSession" type="object">Magento\Checkout\Model\Session</property>
    </type>
    <type name="Magento\Checkout\Controller\Onepage\SaveOrder">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <property name="vendorAgreementsValidator" type="object">Magento\CheckoutAgreements\Model\AgreementsValidator</property>
    </type>
    <type name="Magento\Checkout\Observer\LoadCustomerQuoteObserver">
        <trait type="Ecombricks\VendorCheckout\Observer\LoadCustomerQuoteObserver\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Checkout\Helper\Cart">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Checkout\Helper\Data">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    
    <type name="Magento\Checkout\Model\GuestPaymentInformationManagement">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\VendorQuote\Model\GuestVendorIdProviderTrait" sortOrder="-90" />
        <property name="vendorQuoteIdMaskFactory" type="object">Magento\Quote\Model\QuoteIdMaskFactory</property>
        <property name="vendorCartRepository" type="object">Magento\Quote\Api\CartRepositoryInterface</property>
    </type>
    <type name="Magento\Checkout\Model\GuestShippingInformationManagement">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\VendorQuote\Model\GuestVendorIdProviderTrait" sortOrder="-90" />
        <property name="vendorQuoteIdMaskFactory" type="object">Magento\Quote\Model\QuoteIdMaskFactory</property>
        <property name="vendorCartRepository" type="object">Magento\Quote\Api\CartRepositoryInterface</property>
    </type>
    <type name="Magento\Checkout\Model\GuestTotalsInformationManagement">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\VendorQuote\Model\GuestVendorIdProviderTrait" sortOrder="-90" />
        <property name="vendorQuoteIdMaskFactory" type="object">Magento\Quote\Model\QuoteIdMaskFactory</property>
        <property name="vendorCartRepository" type="object">Magento\Quote\Api\CartRepositoryInterface</property>
    </type>
    <type name="Magento\Checkout\Model\PaymentInformationManagement">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\VendorQuote\Model\VendorIdProviderTrait" sortOrder="-90" />
        <property name="vendorCartRepository" type="object">Magento\Quote\Api\CartRepositoryInterface</property>
    </type>
    <type name="Magento\Checkout\Model\ShippingInformationManagement">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\VendorQuote\Model\VendorIdProviderTrait" sortOrder="-90" />
        <property name="vendorCartRepository" type="object">Magento\Quote\Api\CartRepositoryInterface</property>
    </type>
    <type name="Magento\Checkout\Model\TotalsInformationManagement">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\VendorQuote\Model\VendorIdProviderTrait" sortOrder="-90" />
        <property name="vendorCartRepository" type="object">Magento\Quote\Api\CartRepositoryInterface</property>
    </type>
    
    <type name="Ecombricks\VendorCheckout\Model\PaymentInformationManagement">
        <trait type="Ecombricks\VendorQuote\Model\CartIdProviderTrait" sortOrder="-80" />
        <property name="vendorUserContext" type="object">Magento\Authorization\Model\UserContextInterface</property>
        <property name="vendorCartManagement" type="object">Magento\Quote\Api\CartManagementInterface</property>
    </type>
    <type name="Ecombricks\VendorCheckout\Model\ShippingInformationManagement">
        <trait type="Ecombricks\VendorQuote\Model\CartIdProviderTrait" sortOrder="-80" />
        <property name="vendorUserContext" type="object">Magento\Authorization\Model\UserContextInterface</property>
        <property name="vendorCartManagement" type="object">Magento\Quote\Api\CartManagementInterface</property>
    </type>
    <type name="Ecombricks\VendorCheckout\Model\TotalsInformationManagement">
        <trait type="Ecombricks\VendorQuote\Model\CartIdProviderTrait" sortOrder="-80" />
        <property name="vendorUserContext" type="object">Magento\Authorization\Model\UserContextInterface</property>
        <property name="vendorCartManagement" type="object">Magento\Quote\Api\CartManagementInterface</property>
    </type>
    
</config>

=== anibale11/vendor/app/code/Ecombricks/VendorUser/etc/interception.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© eComBricks. All rights reserved.
 * See LICENSE.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:ecombricks:module:Ecombricks_Interception:etc/interception.xsd">
    <type name="Magento\User\Model\User">
        <trait type="Ecombricks\Vendor\Framework\VendorFlagTrait" sortOrder="-100" />
        <trait type="Ecombricks\Vendor\Framework\Model\VendorFlagTrait" sortOrder="-90" />
        <trait type="Ecombricks\Vendor\Framework\Model\VendorsTrait" sortOrder="-85" />
    </type>
    <type name="Magento\User\Model\UserFactory">
        <trait type="Ecombricks\Vendor\Framework\VendorFlagTrait" sortOrder="-100" />
    </type>
    <type name="Magento\User\Model\ResourceModel\User">
        <trait type="Ecombricks\Vendor\Framework\Model\ResourceModel\Db\VendorFlagTrait" sortOrder="-100" />
        <trait type="Ecombricks\Vendor\Framework\Model\ResourceModel\Db\VendorsTrait" sortOrder="-95" />
        <property name="isVendorTable" type="string">ecombricks_vendor_admin_user</property>
        <property name="vendorIdsTable" type="string">ecombricks_vendor_admin_user_vendor</property>
    </type>
    <type name="Magento\User\Model\ResourceModel\User\Collection">
        <trait type="Ecombricks\Vendor\Framework\VendorFlagTrait" sortOrder="-100" />
        <trait type="Ecombricks\Vendor\Framework\Model\ResourceModel\Db\Collection\VendorFlagTrait" sortOrder="-90" />
        <trait type="Ecombricks\Vendor\Framework\Model\ResourceModel\Db\Collection\VendorsTrait" sortOrder="-85" />
        <property name="isVendorTable" type="string">ecombricks_vendor_admin_user</property>
        <property name="vendorIdsTable" type="string">ecombricks_vendor_admin_user_vendor</property>
    </type>
    <type name="Magento\User\Controller\Adminhtml\User\Role\SaveRole">
        <trait type="Ecombricks\VendorUser\Controller\Adminhtml\User\Role\SaveRole\VendorTrait" sortOrder="-90" />
        <property name="vendorRootAclResource" type="object">Magento\Framework\Acl\RootResource</property>
    </type>
    <type name="Magento\User\Controller\Adminhtml\User\Save">
        <trait type="Ecombricks\VendorUser\Controller\Adminhtml\User\Save\VendorTrait" sortOrder="-90" />
    </type>
</config>
