=== anibale11/vendor/app/code/Ecombricks/Interception/etc/interception.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© eComBricks. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="type" type="typeType" minOccurs="0" maxOccurs="unbounded">
                    <xs:unique name="uniqueTrait">
                        <xs:annotation>
                            <xs:documentation>Trait type should be unique</xs:documentation>
                        </xs:annotation>
                        <xs:selector xpath="trait" />
                        <xs:field xpath="@type" />
                    </xs:unique>
                    <xs:unique name="uniqueProperty">
                        <xs:annotation>
                            <xs:documentation>Property name should be unique</xs:documentation>
                        </xs:annotation>
                        <xs:selector xpath="property" />
                        <xs:field xpath="@name" />
                    </xs:unique>
                </xs:element>
            </xs:choice>
        </xs:complexType>
        <xs:unique name="uniqueType">
            <xs:annotation>
                <xs:documentation>Type name should be unique</xs:documentation>
            </xs:annotation>
            <xs:selector xpath="type" />
            <xs:field xpath="@name" />
        </xs:unique>
    </xs:element>
    <xs:complexType name="typeType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="trait" type="traitType" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="property" type="propertyType" minOccurs="0" maxOccurs="unbounded" />
        </xs:choice>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
    <xs:complexType name="traitType">
        <xs:attribute name="type" type="xs:string" use="required" />
        <xs:attribute name="disabled" type="xs:boolean" use="optional" />
        <xs:attribute name="sortOrder" type="xs:int" use="optional" />
    </xs:complexType>
    <xs:complexType name="propertyType" mixed="true">
        <xs:sequence>
            <xs:element name="item" type="propertyItemType" minOccurs="0" maxOccurs="unbounded">
                <xs:key name="itemName">
                    <xs:selector xpath="item"></xs:selector>
                    <xs:field xpath="@name"></xs:field>
                </xs:key>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="type" type="propertyTypeType" use="required" />
        <xs:attribute name="scope" type="propertyScopeType" use="optional" />
        <xs:attribute name="disabled" type="xs:boolean" use="optional" />
    </xs:complexType>
    <xs:complexType name="propertyItemType" mixed="true">
        <xs:attribute name="name" use="required" />
    </xs:complexType>
    <xs:simpleType name="propertyTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="string" />
            <xs:enumeration value="integer" />
            <xs:enumeration value="float" />
            <xs:enumeration value="boolean" />
            <xs:enumeration value="array" />
            <xs:enumeration value="object" />
            <xs:enumeration value="copy" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="propertyScopeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="private" />
            <xs:enumeration value="protected" />
            <xs:enumeration value="public" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== anibale11/vendor/app/code/Ecombricks/VendorReports/etc/interception.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© eComBricks. All rights reserved.
 * See LICENSE.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:ecombricks:module:Ecombricks_Interception:etc/interception.xsd">
    <type name="Magento\Reports\Model\ResourceModel\Event">
        <trait type="Ecombricks\VendorReports\Model\ResourceModel\Event\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Reports\Model\ResourceModel\Order\CollectionFactory">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Reports\Model\ResourceModel\Product\CollectionFactory">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Reports\Model\ResourceModel\Customer\Collection">
        <trait type="Ecombricks\VendorReports\Model\ResourceModel\Customer\Collection\VendorTrait" sortOrder="-100" />
    </type>
</config>

=== anibale11/vendor/app/code/Ecombricks/VendorConfig/etc/interception.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© eComBricks. All rights reserved.
 * See LICENSE.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:ecombricks:module:Ecombricks_Interception:etc/interception.xsd">
    <type name="Magento\Framework\Url">
        <property name="vendorParameterActionPathPatterns" type="array">
            <item name="adminSystemConfig">#^admin/admin/system_config#</item>
        </property>
    </type>
    <type name="Magento\Framework\App\Config">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\VendorConfig\Framework\App\Config\VendorTrait" sortOrder="-90" />
        <property name="vendorScopeCodeResolver" type="copy">scopeCodeResolver</property>
        <property name="vendorManagement" type="object">Ecombricks\Vendor\Model\VendorManagement</property>
    </type>
    <type name="Magento\Framework\App\Config\Value">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\Vendor\Framework\Model\VendorTrait" sortOrder="-90" />
        <property name="vendorManagement" type="object">Ecombricks\Vendor\Model\VendorManagement</property>
    </type>
    <type name="Magento\Framework\App\Config\ValueFactory">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Config\App\Config\Source\RuntimeConfigSource">
        <trait type="Ecombricks\VendorConfig\App\Config\Source\RuntimeConfigSource\VendorTrait" sortOrder="-100" />
        <property name="vendorCollectionFactory" type="copy">collectionFactory</property>
        <property name="vendorConverter" type="copy">converter</property>
        <property name="vendorScopeCodeResolver" type="copy">scopeCodeResolver</property>
        <property name="vendorManagement" type="object">Ecombricks\Vendor\Model\VendorManagement</property>
    </type>
    <type name="Magento\Config\Model\ResourceModel\Config\Data">
        <trait type="Ecombricks\Vendor\Framework\Model\ResourceModel\Db\VendorTrait" sortOrder="-90" />
        <property name="vendorMainTable" type="string">ecombricks_vendor_core_config_data</property>
    </type>
    <type name="Magento\Config\Model\ResourceModel\Config\Data\Collection">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\Vendor\Framework\Model\ResourceModel\Db\Collection\VendorTrait" sortOrder="-90" />
        <property name="vendorManagement" type="object">Ecombricks\Vendor\Model\VendorManagement</property>
        <property name="vendorMainTable" type="string">ecombricks_vendor_core_config_data</property>
    </type>
    <type name="Magento\Config\Model\Config\SchemaLocator">
        <trait type="Ecombricks\VendorConfig\Model\Config\SchemaLocator\VendorTrait" sortOrder="-100" />
        <property name="vendorUrnResolver" type="object">Magento\Framework\Config\Dom\UrnResolver</property>
    </type>
    <type name="Magento\Config\Model\Config">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Config\Model\Config\Factory">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Config\Model\Config\Structure">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Config\Model\Config\Structure\Element\Iterator">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Config\Model\Config\Structure\Element\FlyweightFactory">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Config\Model\Config\Structure\AbstractElement">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\VendorConfig\Model\Config\Structure\AbstractElement\VendorTrait" sortOrder="-90" />
    </type>
    <type name="Magento\Config\Model\Config\BackendFactory">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Config\Model\Config\SourceFactory">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Config\Model\Config\Source\Email\Template">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Config\Block\System\Config\Form">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Config\Block\System\Config\Form\Field">
        <trait type="Ecombricks\VendorConfig\Block\System\Config\Form\Field\VendorTrait" sortOrder="-100" />
    </type>
    <type name="Magento\Config\Controller\Adminhtml\System\AbstractConfig">
        <trait type="Ecombricks\VendorConfig\Controller\Adminhtml\System\AbstractConfig\VendorTrait" sortOrder="-80" />
    </type>
</config>

=== anibale11/vendor/app/code/Ecombricks/VendorGiftMessage/etc/interception.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© eComBricks. All rights reserved.
 * See LICENSE.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:ecombricks:module:Ecombricks_Interception:etc/interception.xsd">
    
    <type name="Magento\GiftMessage\Model\GuestCartRepository">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\VendorQuote\Model\GuestVendorIdProviderTrait" sortOrder="-90" />
        <property name="vendorQuoteIdMaskFactory" type="object">Magento\Quote\Model\QuoteIdMaskFactory</property>
        <property name="vendorCartRepository" type="object">Magento\Quote\Api\CartRepositoryInterface</property>
    </type>
    <type name="Magento\GiftMessage\Model\GuestItemRepository">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\VendorQuote\Model\GuestVendorIdProviderTrait" sortOrder="-90" />
        <property name="vendorQuoteIdMaskFactory" type="object">Magento\Quote\Model\QuoteIdMaskFactory</property>
        <property name="vendorCartRepository" type="object">Magento\Quote\Api\CartRepositoryInterface</property>
    </type>
    <type name="Magento\GiftMessage\Model\CartRepository">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\VendorQuote\Model\VendorIdProviderTrait" sortOrder="-90" />
        <property name="vendorCartRepository" type="object">Magento\Quote\Api\CartRepositoryInterface</property>
    </type>
    <type name="Magento\GiftMessage\Model\ItemRepository">
        <trait type="Ecombricks\Vendor\Framework\VendorTrait" sortOrder="-100" />
        <trait type="Ecombricks\VendorQuote\Model\VendorIdProviderTrait" sortOrder="-90" />
        <property name="vendorCartRepository" type="object">Magento\Quote\Api\CartRepositoryInterface</property>
    </type>
    
</config>
